spring:
  jpa:
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 100
          time_zone: UTC

    hibernate:
      ddl-auto: none


---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/playground
    username: postgres
    password: admin

